name: Azure Static Web Apps CI/CD

on:
  # Run this GitHub Action every time someone force-pushes to main
  # (note:  this will only run when pull-requests into main get approved & closed out 
  #    if main is a branch that has force-push protection enabled).
  # (note:  we could also make this '- "**"' instead of '- main' to let every branch ever created in the repository 
  #   cause Azure SWA to build URLs off of the branches, but 2 comments about that:)
  #    1. Between named branches and numbered pull requests, Azure Static Web Apps will refuse to build 
  #       new nonproduction URLs for you once you exceed your plan's limits (3 for free; 10 for standard).
  #    2. Having Azure build a site with a branch name in its URL based on the existence of the branch AND 
  #       having Azure also build a site with a pull-request number in its URL based on the existence of a pull request 
  #       from that branch into some other branch is wasteful, so you probably either want just something like '- "**"' 
  #       with no "pull_request" version of this "on" or you want some explicit set of long-running branches like 
  #       ' - [main, staging, development]' under the "push: branches:" property of "on:", 
  #       followed by a "pull_request" version that only bothers to build preview URLs for other branches if they've got an 
  #       open pull request into a specific long-running branch (or set of long-running branches).
  push:
    branches:
      - main
  # Run this GitHub Action every time someone opens, synchronizes, reopens, or closes a pull-request aimed at main.
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  # Allow this GitHub Action to be run manually from this repository's Actions tab
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    # Make sure preview URL can get written into pull request comment
    # https://www.aaron-powell.com/posts/2022-08-09-fixing-when-swa-prs-cant-add-comments/
    permissions: 
      id-token: write
      contents: read
      pull-requests: write
    # Although not used in this repository, make the URL of the website Azure builds available to whatever "job" you might 
    # sequence next with GitHub Actions, such as some end-to-end testing in Selenium, Playwright, etc. as, 
    # say, a "needs.build_and_deploy_job.outputs.the_just_built_static_web_app_url" GitHub Actions variable.
    # https://www.aaron-powell.com/posts/2022-04-08-accessing-a-swa-url-from-github/actions/
    outputs:
      the_just_built_static_web_app_url: ${{ steps.builddeploy.outputs.static_web_app_url }}
    steps:
      # Make a copy of this repository visible to the GitHub Actions execution context.
      - uses: actions/checkout@v2
        with:
          submodules: true
      # Grab the correct HTML files from this repository and push them up to Azure Static Web Apps.
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.MY_AZURE_SWA_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/src/web" # App source code path
          api_location: "/src/api" # Api source code path - optional
          output_location: "/output" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      # I think this is the step that destroys preview URLs created during pull requests?
      # https://learn.microsoft.com/en-us/azure/static-web-apps/preview-environments
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.MY_AZURE_SWA_DEPLOYMENT_TOKEN }}
          action: "close"
